### PR TITLE
Add DnsCaaResource

### PR DESCRIPTION
**Pull request by zhangzhezh**
Add DnsCaaResource

### CODE REVIEW

**Comment by alanedwardes** [comment]
Hi,

Thank you for the contribution! I decided to implement this a different way (https://github.com/alanedwardes/Ae.Dns/commit/23701ecd61fd1e23ad6eba2b05c2b3b502157555) for a couple of reasons:
- I think the string parsing here is too verbose - there are already helpers in `DnsByteExtensions` which significantly simplify the code
- The value is not actually a string according to [RFC 6844](https://datatracker.ietf.org/doc/html/rfc6844#section-5.1) - it certainly can be a string (and I'd assume it is in the vast majority of cases), but it doesn't have to be. So I made this an array of bytes, and the caller must use `Encoding.ASCII.GetString` on the contents if they know it to be a string.

Thank you for putting this record type on my radar.

**Comment by zhangzhezh** [comment]
OK,Do it your way alan,thank you for your work,and BTW,string TXT record have problem,when use dig to test, it's will respone "xxxxxxxxxxx" ""          ,this could fix          public virtual void WriteBytes(Memory<byte> bytes, ref int offset)
        {
           // DnsByteExtensions.ToBytes(Entries.ToArray(), bytes, ref offset);
            byte[] valueBytes = Encoding.UTF8.GetBytes(Entries);

            // Ensure the value fits in a single TXT record string
            if (valueBytes.Length > 255)
            {
                throw new ArgumentException("Value is too long to fit in a single DNS TXT record string.");
            }

            // Write the length byte
            bytes.Span[offset++] = (byte)valueBytes.Length;

            // Write the value bytes
            foreach (byte b in valueBytes)
            {
                bytes.Span[offset++] = b;
            }
        }

**Comment by alanedwardes** [comment]
Hmm, can you raise an issue detailing the problem with steps to reproduce this? For example, a sample packet or example query to trigger the bug.

**Comment by alanedwardes** [comment]
Never mind, I see exactly what you mean: https://github.com/alanedwardes/Ae.Dns/issues/26

**Pull request closed without merging**
